version: '3.7'

services:
  redis:
    image: redis:3.2-alpine
    volumes:
        - redis_data:/data
  django_application:
    build: ./django_app
    volumes:
        - ./django_app/:/code/src/django_app/
        - static_volume:/code/src/django_app/staticfiles
    expose:
        - 8000
    env_file:
        - environment_files/local.env
    depends_on:
        - redis
  webapp:
    build: ./angular-form
    volumes:
        - static_volume:/code/src/django_app/staticfiles
        - ./angular-form/:/code/src/webapp/
    ports: 
        - 80:80
    depends_on:
        - django_application
volumes:
  static_volume:
  redis_data:

